Repository Pandora-IsoMemo/iso-app, pull requests merged in 2022-09, with the labels that each got.

#48 Feat/19 operator r name change
  DESCRIPTION
  R/03-mapDiff.R
  inst/app/server.R
Labels: documentation

#57 Feat/8 input box time
  DESCRIPTION
  NEWS.md
  R/03-modelResults3D.R
  R/03-modelResults3DKernel.R
  man/sliderAndNumericInputServer.Rd
  man/sliderAndNumericInputUI.Rd
Labels: 2022: KernerTimeR and TimeR, IsoMemo App

#59 Feat/12 decimal point
  DESCRIPTION
  NEWS.md
  R/01-plotMap.R
  R/02-modules-modelResultHelpers.R
  R/03-modelResults2D.R
  R/03-modelResults2DKernel.R
  R/03-modelResults3D.R
  R/03-modelResults3DKernel.R
  R/03-modelResultsSpread.R
  man/addFormattedAxis.Rd
  man/centerEstimateServer.Rd
  man/centerEstimateUI.Rd
  man/formatTimeCourseServer.Rd
  man/formatTimeCourseUI.Rd
  man/plotTimeCourse.Rd
  tests/testthat/test-plotMap.R
Labels: 2022: All graphical models in IsoMemoapp (New)
