Repository Pandora-IsoMemo/iso-app, pull requests merged in 2023-04, with the labels that each got.

#130 Feat/13 leaflet point symbol
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/00-Namespace.R
  R/01-fieldTypes.R
  R/02-leafletPointSettings.R
  R/02-leafletSettings.R
  R/03-interactiveMap.R
  R/03-modelResults2D.R
  R/03-modelResults2DKernel.R
  R/03-modelResults3D.R
  R/03-modelResults3DKernel.R
  R/03-modelResultsSpread.R
  inst/app/www/testFile17f72eda0249.png
  man/createPchPoints.Rd
  man/createPchPointsVec.Rd
  man/getHTMLFromPath.Rd
  man/getPointSize.Rd
  man/getPointSymbols.Rd
  man/pointSymbolServer.Rd
  man/pointSymbolUI.Rd
  man/removeOldIcons.Rd
  tests/testthat/kernelTimeR_testModel.rds
  tests/testthat/test-interactiveMapDraw.R
  tests/testthat/test-module-leafletPointSettings.R
Labels: IsoMemo App, 2022-WP2-2

#136 Feature/54 requested clustering changes
  DESCRIPTION
  NEWS.md
  R/01-estimateMap.R
  R/01-plotMap.R
  R/03-modelResults2DKernel.R
  R/03-modelResults3DKernel.R
Labels: IsoMemo App, 2022-WP2-4

#141 #139 reset model output when changing the data source
  DESCRIPTION
  R/03-modelResults2D.R
  R/03-modelResults2DKernel.R
  R/03-modelResults3D.R
  R/03-modelResults3DKernel.R
  R/03-modelResultsAssign.R
  R/03-modelResultsSpread.R
Labels: bug, Support: Bug fixing
