Repository Pandora-IsoMemo/iso-app, pull requests merged in 2023-05, with the labels that each got.

#143 Bug/122: extract and apply convertLatLongWrapper
  DESCRIPTION
  NAMESPACE
  R/00-Namespace.R
  R/01-convertLatLong.R
  R/01-estimateMap.R
  R/01-validateModelInput.R
  R/02-locationFields.R
  R/03-dataExplorer.R
  R/03-mapSim.R
  man/convertLatLongWrapper.Rd
  man/getDefaultCoordColumn.Rd
  man/locationFieldsServer.Rd
  man/locationFieldsUI.Rd
  man/putNewLatLongToBegin.Rd
  tests/testthat/test-dataExplorer.R
Labels: bug, Support: Bug fixing

#146 set default API_BASE_URL
  .Renviron
  DESCRIPTION
  NEWS.md
  R/01-isomemoAPI.R
Labels: bug, Support: Bug fixing

#147 Bug/110 convert date to numeric
  DESCRIPTION
  NEWS.md
  R/01-estimateMap.R
  R/01-validateModelInput.R
  R/03-modelResults3DKernel.R
Labels: bug, Support: Bug fixing

#151 Version 23.05.2: Feat/133 borders and names on maps
  DESCRIPTION
  NEWS.md
  R/02-leafletSettings.R
Labels: IsoMemo App, 2022-WP2-2

#153 always try numeric date columns
  DESCRIPTION
  R/01-estimateMap.R
Labels: bug, IsoMemo App

#149 Feature/135 apply functions from datatools
  DESCRIPTION
  NAMESPACE
  NEWS.md
  R/00-Namespace.R
  R/01-isomemoAPI.R
  man/getMappingTable.Rd
  man/getRemoteData.Rd
  tests/testthat/test-module-ELEMENTS.R
  tests/testthat/test-module-leafletPointSettings.R
Labels: IsoMemo App, 2022-WP2-2

#158 Version 23.04.1.10: fix if no connection
  .gitignore
  DESCRIPTION
  NEWS.md
  R/03-dataExplorer.R
  inst/app/server.R
  tests/testthat/test-module-importData.R
Labels: bug, Support: Bug fixing
